### ISSUE TITLE
Fatal error: Uncaught TelegramBot\Api\HttpException: Not Found 

### ISSUE THREAD

**Issue by cephpiter** [inverse/termin#39]
Hey, great project!

I set up the project to send notifications through Telegram.
When a slot was available, the notification failed with the following trace
```
[2021-10-31T02:30:07.423424+00:00] termin.INFO: Found availability for Vaterschaftsanerkennung @ 2021-11-23T00:00:00+01:00 [] []

Fatal error: Uncaught TelegramBot\Api\HttpException: Not Found in /app/vendor/telegram-bot/api/src/BotApi.php:286
Stack trace:
#0 /app/vendor/telegram-bot/api/src/BotApi.php(263): TelegramBot\Api\BotApi::curlValidate(Resource id #67, '{"ok":false,"er...')
#1 /app/vendor/telegram-bot/api/src/BotApi.php(232): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /app/vendor/telegram-bot/api/src/BotApi.php(342): TelegramBot\Api\BotApi->call('sendMessage', Array)
#3 /app/src/Notifier/TelegramNotifier.php(25): TelegramBot\Api\BotApi->sendMessage(227284883, 'Vaterschaftsane...', 'markdown')
#4 /app/src/Notifier/MultiNotifier.php(33): Inverse\Termin\Notifier\TelegramNotifier->notify('Vaterschaftsane...', 'https://service...', Object(DateTime))
#5 /app/src/Termin.php(45): Inverse\Termin\Notifier\MultiNotifier->notify('Vaterschaftsane...', 'https://service...', Object(DateTime))
#6 /app/app.php(15): Inverse\Termin\Termin->run(Array)
#7 {main}
  thrown in /app/vendor/telegram-bot/api/src/BotApi.php on line 286
```

Do you have any leads on what is going on?

I tried to send also directly the message like this

on TelegramNotifier.php line 25
```php
$this->botApi->sendMessage(mychatid, "Test", 'markdown');
```

And received a similar error 
```
❯ php app.php 
PHP Fatal error:  Uncaught TelegramBot\Api\HttpException: Not Found in /opt/termin/termin/vendor/telegram-bot/api/src/BotApi.php:286
Stack trace:
#0 /opt/termin/termin/vendor/telegram-bot/api/src/BotApi.php(263): TelegramBot\Api\BotApi::curlValidate()
#1 /opt/termin/termin/vendor/telegram-bot/api/src/BotApi.php(232): TelegramBot\Api\BotApi->executeCurl()
#2 /opt/termin/termin/vendor/telegram-bot/api/src/BotApi.php(342): TelegramBot\Api\BotApi->call()
#3 /opt/termin/termin/src/Notifier/TelegramNotifier.php(26): TelegramBot\Api\BotApi->sendMessage()
#4 /opt/termin/termin/src/Notifier/MultiNotifier.php(33): Inverse\Termin\Notifier\TelegramNotifier->notify()
#5 /opt/termin/termin/src/Termin.php(40): Inverse\Termin\Notifier\MultiNotifier->notify()
#6 /opt/termin/termin/app.php(15): Inverse\Termin\Termin->run()
#7 {main}
  thrown in /opt/termin/termin/vendor/telegram-bot/api/src/BotApi.php on line 286
```

**Comment by inverse** [comment]
I must have missed this message - Check the `README` - I updated it recently with more detailed output on how to get your chatID etc - perhaps it could be around not interacting with the bot first or something?

**Comment by inverse** [comment]
@cephpiter ^^

**Comment by inverse** [comment]
Closing due to stale issue, please reopen if you face this again.
